<?php

namespace Rhubarb\Leaf\TwigView\Docs\Examples\SimpleTwigView;

use Rhubarb\Leaf\Leaves\Leaf;
use Rhubarb\Leaf\Leaves\LeafModel;

/**
 * @property LeafModel $model
 */
class TwigExample extends Leaf
{

    protected function getViewClass()
    {
        return TwigExampleView::class;
    }

    protected function createModel()
    {
        return new LeafModel();
    }

    protected function onModelCreated()
    {
        parent::onModelCreated(); // TODO: Change the autogenerated stub
    }
}